/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 beachAnimation\public\wp-content\uploads\r3f\beach-animation4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BeachAnimation3(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/wp-content/uploads/r3f/beach-animation3.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.077, 0.039, -0.794]} rotation={[Math.PI / 2, 0, 0.171]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="mesh_070" geometry={nodes.mesh_070.geometry} material={materials._070_Robert} skeleton={nodes.mesh_070.skeleton} />
        </group>
        <group name="palm_tree_01003" position={[2.743, 0.373, -7.04]} rotation={[0, -0.451, 0]} scale={[0.048, 0.046, 0.048]}>
          <mesh name="palm_tree_01-Mesh003" geometry={nodes['palm_tree_01-Mesh003'].geometry} material={materials['795548.003']} />
          <mesh name="palm_tree_01-Mesh003_1" geometry={nodes['palm_tree_01-Mesh003_1'].geometry} material={materials['8BC34A.003']} />
          <mesh name="palm_tree_01-Mesh003_2" geometry={nodes['palm_tree_01-Mesh003_2'].geometry} material={materials['DD9944.003']} />
          <mesh name="palm_tree_01-Mesh003_3" geometry={nodes['palm_tree_01-Mesh003_3'].geometry} material={materials.metalMedium} />
          <mesh name="palm_tree_01-Mesh003_4" geometry={nodes['palm_tree_01-Mesh003_4'].geometry} material={materials.metalDark} />
          <mesh name="palm_tree_01-Mesh003_5" geometry={nodes['palm_tree_01-Mesh003_5'].geometry} material={materials.metal} />
          <mesh name="palm_tree_01-Mesh003_6" geometry={nodes['palm_tree_01-Mesh003_6'].geometry} material={materials.lambert3SG} />
          <mesh name="palm_tree_01-Mesh003_7" geometry={nodes['palm_tree_01-Mesh003_7'].geometry} material={materials['795548']} />
          <mesh name="palm_tree_01-Mesh003_8" geometry={nodes['palm_tree_01-Mesh003_8'].geometry} material={materials['8BC34A']} />
          <mesh name="palm_tree_01-Mesh003_9" geometry={nodes['palm_tree_01-Mesh003_9'].geometry} material={materials.DD9944} />
          <mesh name="palm_tree_01-Mesh003_10" geometry={nodes['palm_tree_01-Mesh003_10'].geometry} material={materials['Material.006']} />
          <mesh name="palm_tree_01-Mesh003_11" geometry={nodes['palm_tree_01-Mesh003_11'].geometry} material={materials.Mat} />
          <mesh name="palm_tree_01-Mesh003_12" geometry={nodes['palm_tree_01-Mesh003_12'].geometry} material={materials['795548.001']} />
          <mesh name="palm_tree_01-Mesh003_13" geometry={nodes['palm_tree_01-Mesh003_13'].geometry} material={materials['8BC34A.001']} />
          <mesh name="palm_tree_01-Mesh003_14" geometry={nodes['palm_tree_01-Mesh003_14'].geometry} material={materials['DD9944.001']} />
          <mesh name="palm_tree_01-Mesh003_15" geometry={nodes['palm_tree_01-Mesh003_15'].geometry} material={materials['795548.002']} />
          <mesh name="palm_tree_01-Mesh003_16" geometry={nodes['palm_tree_01-Mesh003_16'].geometry} material={materials['8BC34A.002']} />
          <mesh name="palm_tree_01-Mesh003_17" geometry={nodes['palm_tree_01-Mesh003_17'].geometry} material={materials['DD9944.002']} />
          <mesh name="palm_tree_01-Mesh003_18" geometry={nodes['palm_tree_01-Mesh003_18'].geometry} material={materials['795548.004']} />
          <mesh name="palm_tree_01-Mesh003_19" geometry={nodes['palm_tree_01-Mesh003_19'].geometry} material={materials['8BC34A.004']} />
          <mesh name="palm_tree_01-Mesh003_20" geometry={nodes['palm_tree_01-Mesh003_20'].geometry} material={materials['DD9944.004']} />
          <mesh name="palm_tree_01-Mesh003_21" geometry={nodes['palm_tree_01-Mesh003_21'].geometry} material={materials['795548.005']} />
          <mesh name="palm_tree_01-Mesh003_22" geometry={nodes['palm_tree_01-Mesh003_22'].geometry} material={materials['8BC34A.005']} />
          <mesh name="palm_tree_01-Mesh003_23" geometry={nodes['palm_tree_01-Mesh003_23'].geometry} material={materials['DD9944.005']} />
          <mesh name="palm_tree_01-Mesh003_24" geometry={nodes['palm_tree_01-Mesh003_24'].geometry} material={materials['795548.006']} />
          <mesh name="palm_tree_01-Mesh003_25" geometry={nodes['palm_tree_01-Mesh003_25'].geometry} material={materials['8BC34A.006']} />
          <mesh name="palm_tree_01-Mesh003_26" geometry={nodes['palm_tree_01-Mesh003_26'].geometry} material={materials['DD9944.006']} />
          <mesh name="palm_tree_01-Mesh003_27" geometry={nodes['palm_tree_01-Mesh003_27'].geometry} material={materials['795548.007']} />
          <mesh name="palm_tree_01-Mesh003_28" geometry={nodes['palm_tree_01-Mesh003_28'].geometry} material={materials['8BC34A.007']} />
          <mesh name="palm_tree_01-Mesh003_29" geometry={nodes['palm_tree_01-Mesh003_29'].geometry} material={materials['DD9944.007']} />
          <mesh name="palm_tree_01-Mesh003_30" geometry={nodes['palm_tree_01-Mesh003_30'].geometry} material={materials.mat21} />
          <mesh name="palm_tree_01-Mesh003_31" geometry={nodes['palm_tree_01-Mesh003_31'].geometry} material={materials.mat12} />
          <mesh name="palm_tree_01-Mesh003_32" geometry={nodes['palm_tree_01-Mesh003_32'].geometry} material={materials.mat8} />
          <mesh name="palm_tree_01-Mesh003_33" geometry={nodes['palm_tree_01-Mesh003_33'].geometry} material={materials.mat5} />
          <mesh name="palm_tree_01-Mesh003_34" geometry={nodes['palm_tree_01-Mesh003_34'].geometry} material={materials['lambert3SG.001']} />
          <mesh name="palm_tree_01-Mesh003_35" geometry={nodes['palm_tree_01-Mesh003_35'].geometry} material={materials.lambert2SG} />
          <mesh name="palm_tree_01-Mesh003_36" geometry={nodes['palm_tree_01-Mesh003_36'].geometry} material={materials.lambert4SG} />
        </group>
        <group name="Null1" position={[2.521, 4.337, -1.94]} rotation={[-0.118, 0.006, -0.051]} scale={0.03}>
          <mesh name="Null1-Mesh" geometry={nodes['Null1-Mesh'].geometry} material={materials['Mat.1']} />
          <mesh name="Null1-Mesh_1" geometry={nodes['Null1-Mesh_1'].geometry} material={materials['Mat.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wp-content/uploads/r3f/beach-animation3.glb')
