/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\beach-animation1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BeachAnimation(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/wp-content/uploads/r3f/beach-animation1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.077, 0.039, -0.794]} rotation={[Math.PI / 2, 0, 0.171]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="mesh_070" geometry={nodes.mesh_070.geometry} material={materials._070_Robert} skeleton={nodes.mesh_070.skeleton} />
        </group>
        <group name="laptop_1" position={[0.562, 1.875, 0.641]} rotation={[0, -0.171, 0]} scale={5.462}>
          <mesh name="laptop_3" geometry={nodes.laptop_3.geometry} material={materials.metalMedium} />
          <mesh name="laptop_3_1" geometry={nodes.laptop_3_1.geometry} material={materials.metalDark} />
          <mesh name="laptop_3_2" geometry={nodes.laptop_3_2.geometry} material={materials.metal} />
        </group>
        <mesh name="Beach_Chair1" geometry={nodes.Beach_Chair1.geometry} material={materials.lambert3SG} position={[3.016, 4.278, -1.78]} scale={0.022} />
        <mesh name="Beach_Chair" geometry={nodes.Beach_Chair.geometry} material={materials.lambert3SG} position={[3.016, 4.826, -1.78]} scale={0.022} />
        <group name="Beach_Umbrella" position={[3.016, 4.826, -1.78]} scale={0.022}>
          <mesh name="Beach_Umbrella_1" geometry={nodes.Beach_Umbrella_1.geometry} material={materials.lambert3SG} />
          <mesh name="Beach_Umbrella_1_1" geometry={nodes.Beach_Umbrella_1_1.geometry} material={materials.lambert5SG} />
        </group>
        <group name="palm_tree_01" position={[-6.201, 0.022, -1.22]} rotation={[Math.PI, -1.047, Math.PI]} scale={0.063}>
          <mesh name="palm_tree_01-Mesh" geometry={nodes['palm_tree_01-Mesh'].geometry} material={materials['795548']} />
          <mesh name="palm_tree_01-Mesh_1" geometry={nodes['palm_tree_01-Mesh_1'].geometry} material={materials['8BC34A']} />
          <mesh name="palm_tree_01-Mesh_2" geometry={nodes['palm_tree_01-Mesh_2'].geometry} material={materials.DD9944} />
        </group>
        <mesh name="Cube003_Cube002" geometry={nodes.Cube003_Cube002.geometry} material={materials['Material.006']} position={[-7.17, 1.471, -9.327]} />
        <mesh name="Node" geometry={nodes.Node.geometry} material={materials.Mat} position={[-4.571, -3.12, -3.275]} scale={0.049} />
      </group>
    </group>
  )
}

useGLTF.preload('/wp-content/uploads/r3f/beach-animation1.glb')
